import data

def currencies():
    dictionary = {
        "united states dollar" : data.usd,
        "usd" : data.usd,
        "united states" : data.usd,
        "us dollar" : data.usd,
        "american dollar" : data.usd,
        "canadian dollar" : data.cad,
        "cad" : data.cad,
        "swiss franc": data.chf,
        "chf" : data.chf,
        "australian dollar" : data.aud,
        "aud" : data.aud,
        "au" : data.aud,
        "aussie" : data.aud,
        "japanese yen" : data.jpy,
        "jpy" : data.jpy,
        "new zealand" : data.nzd,
        "nzd" : data.nzd,
        "euro" : data.eur, 
        "eur" : data.eur,
        "pound" : data.gbp,
        "gbp" : data.gbp,
        "swedish krona" : data.sek,
        "sek" : data.sek,
        "danish krone" : data.dkk,
        "dkk" : data.dkk,
        "krona norwegia" : data.nok,
        "nok" : data.nok,
        "singapore" : data.sgd,
        "sgd" : data.sgd,
        "czech koruna" : data.czk,
        "czk" : data.czk,
        "hong kong" : data.hkd,
        "hkd" : data.hkd,
        "mexican" : data.mxn,
        "mxn" : data.mxn,
        "zloty" : data.pln,
        "pln" : data.pln,
        "ruble" : data.rub,
        "rub" : data.rub,
        "turkish lira" : data._try,
        "try" : data._try,
        "rand" : data.zar,
        "zar" : data.zar,
        "yuan" : data.cnh,
        "cnh" : data.cnh,
        "united arab emirates dirham" : data.aed,
        "aed" : data.aed,
        "afghanistan afghani" : data.afn,
        "afn" : data.afn,
        "albania lek" : data.all,
        "all" : data.all,
        "armenia dram" : data.amd,
        "amd" : data.amd,
        "netherlands antilles guilder" : data.ang,
        "ang" : data.ang,
        "angola kwanza" : data.aoa,
        "aoa" : data.aoa,
        "argentinian peso" : data.ars,
        "ars" : data.ars,
    }

    return dictionary

def countries():
    dictionary = {
        "united states" : data.united_states,
        "us" : data.united_states,
        "america" : data.united_states,
        "canada" : data.canada,
        "ca" : data.canada,
        "switzerland" : data.switzerland,
        "ch" : data.switzerland,
        "australia" : data.australia,
        "au" : data.australia,
        "aus" : data.australia,
        "japan" : data.japan,
        "jp" : data.japan,
        "new zealand" : data.new_zealand,
        "nz" : data.new_zealand,
        "united kingdom" : data.united_kingdom,
        "uk" : data.united_kingdom,
        "sweden" : data.sweden,
        "se" : data.sweden,
        "norway" : data.norway,
        "no" : data.norway,
        "czech republic" : data.czech_republic,
        "cz" : data.czech_republic,
        "mexico" : data.mexico,
        "mx" : data.mexico,
        "poland" : data.poland,
        "pl" : data.poland,
        "russia" : data.russia,
        "ru" : data.russia,
        "turkey" : data.turkey,
        "tr" : data.turkey,
        "south africa" : data.south_africa,
        "za" : data.south_africa,
        "china" : data.china,
        "cn" : data.china,
        "united arab emirates" : data.united_arab_emirates,
        "arab emirates" : data.united_arab_emirates,
        "ae" : data.united_arab_emirates,
        "afghanistan" : data.afghanistan,
        "af" : data.afghanistan,
        "albania" : data.albania,
        "al" : data.albania,
        "armenia" : data.armenia,
        "am" : data.armenia,
        "netherlands" : data.netherlands,
        "nl" : data.netherlands,
        "angola" : data.angola,
        "ao" : data.angola,
        "argentina" : data.argentina,
        "ar" : data.argentina
    }

    return dictionary

    def languages():
        dictionary = {
            "english" : data.english,
            "eng" : data.english,
        }

    return dictionary