def currencies():
    dictionary = {
        "united states dollar" : "usd",
        "usd" : "usd",
        "united states" : "usd",
        "us dollar" : "usd",
        "american dollar" : "usd",
        "canadian dollar" : "cad",
        "cad" : "cad",
        "swiss franc": "chf",
        "chf" : "chf",
        "australian dollar" : "aud",
        "aud" : "aud",
        "au" : "aud",
        "aussie" : "aud",
        "japanese yen" : "jpy",
        "jpy" : "jpy",
        "new zealand" : "nzd",
        "nzd" : "nzd",
        "euro" : "eur", 
        "eur" : "eur",
        "pound" : "gbp",
        "gbp" : "gbp",
        "swedish krona" : "sek",
        "sek" : "sek",
        "danish krone" : "dkk",
        "dkk" : "dkk",
        "krona norwegia" : "nok",
        "nok" : "nok",
        "singapore" : "sgd",
        "sgd" : "sgd",
        "czech koruna" : "czk",
        "czk" : "czk",
        "hong kong" : "hkd",
        "hkd" : "hkd",
        "mexican" : "mxn",
        "mxn" : "mxn",
        "zloty" : "pln",
        "pln" : "pln",
        "ruble" : "rub",
        "rub" : "rub",
        "turkish lira" : "try",
        "try" : "try",
        "rand" : "zar",
        "zar" : "zar",
        "yuan" : "cnh",
        "cnh" : "cnh",
        "united arab emirates dirham" : "aed",
        "aed" : "aed",
        "afghanistan afghani" : "afn",
        "afn" : "afn",
        "albania lek" : "all",
        "all" : "all",
        "armenia dram" : "amd",
        "amd" : "amd",
        "netherlands antilles guilder" : "ang",
        "ang" : "ang",
        "angola kwanza" : "aoa",
        "aoa" : "aoa",
        "argentinian peso" : "ars",
        "ars" : "ars",
    }

    return dictionary

def countries():
    dictionary = {
        "united states" : "us",
        "america" : "us",
        "canada" : "ca",
        "switzerland" : "ch",
        "australia" : "au",
        "aus" : "au",
        "japan" : "jp",
        "new zealand" : "nz",
        "united kingdom" : "uk",
        "sweden" : "se",
        "norway" : "no",
        "czech republic" : "cz",
        "mexico" : "mx",
        "poland" : "pl",
        "russia" : "ru",
        "turkey" : "tr",
        "south africa" : "za",
        "china" : "cn",
        "united arab emirates" : "ae",
        "arab emirates" : "ae",
        "afghanistan" : "af",
        "albania" : "al",
        "armenia" : "am",
        "netherlands" : "nl",
        "angola" : "ao",
        "argentina" : "ar"
    }

    return dictionary

def languages():
        dictionary = {
            "english" : "en",
            "eng" : "en",
            "arabic" : "ar",
            "ar" : "ar",
            "chinese" : "zh",
            "zh" : "zh",
            "czech" : "cs",
            "cs" : "cs",
            "danish" : "da",
            "da" : "da",
            "dutch" : "nl",
            "nl" : "nl",
            "french" : "fr",
            "fr" : "fr",
            "german" : "de",
            "de" : "de",
            "deutsch" : "de",
            "hindi" : "hi",
            "hi" : "hi",
            "hebrew" : "he",
            "he" : "he",
            "italian" : "it",
            "it" : "it",
            "japanese" : "ja",
            "ja" : "ja",
            "korean" : "ko",
            "ko" : "ko",
            "portuguese" : "pt",
            "pt" : "pt",
            "russian" : "ru",
            "ru" : "ru",
            "slovak" : "sk",
            "sk" : "sk",
            "spanish" : "es",
            "es" : "es"
        }

        return dictionary